# name: workflow
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Установить PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '7.1'
#       # - name: Запустить тесты
#       #   run: vendor/bin/phpunit
#       # - name: Деплой на сервер
#       #   uses: easingthemes/ssh-deploy@v2.2.9
#       #   with:
#       #     ssh-private-key: ${{ secrets.SSH_ONLINE_QUIZ }}
#       #     ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
#       #     remote-username: 'cn73246'
#       #     remote-host: '185.114.245.100'
#       #     local-path:
#       #     remote-path: '/online-quiz/public_html'

# name: upload-to-timeweb
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Установить PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'

      - name: Установить ssh-askpass
        run: sudo apt-get install ssh-askpass

      - name: Загрузить файлы на сервер
        run: rsync -ravz --progress --delete "C:\OpenServer\domains\online-quiz" cn73246@185.114.245.100:/public_html
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Установить права на загруженные файлы
        run: ssh cn73246@185.114.245.100 "chmod -R 755 /public_html"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Проверить результаты выполнения каждого шага
        run: echo "Шаг успешно выполнен"
