name: workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Установить PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
      # - name: Запустить тесты
      #   run: vendor/bin/phpunit
      - name: Деплой на сервер
        uses: easingthemes/ssh-deploy@v2.2.9
        with:
          ssh-private-key: ${{ b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAuSh8xAZqwezcrgb/hWLrwE58cciH0/3CNpmEgjC0wlGrgZ2F+ORi
qqQfQRdlQrGPx+St8uTy0SJKQdYJOjX46/dTijR6nQG5ZyqH7uwwq/+LZ9O/jLMjrKPosd
UOPV7DoVG7ZiwWefm5IJvgc7KDBaQ3J3wpReGCdEGEmNI+MmRYa8SNZuk2HscBoBuO8DdI
AS2z2za6FAWeP/ok1syXqzdjbuLMrQRlx2yxrIIrOrEE+raLjZN4vibRwtfB3HNs1mhmfn
tShRNtvRPwHsXdfP6IX8sOxh2vT3hjyzWB9IMPFpJy2twrk7/HKIsBc/Co0K31KoxX2nE1
JTfvKMgTJ+bcoDEPe+z0jON7iuhQBn9vOzYAkmFURgQkbfNN7XGRhukzcwepGyib54Nt0s
tKNFBq/RuJA+cCLmnH0GoRrONINvxaNrikTj4J9Y5K9+RlG7e4YJI9Yr9eJ0WpR6LXC2fl
h70Lwa1ER6w0jfIqZg3ekCjNWl+pFlrls8ERwsiESRqw0Q1vMlsiNHSyTUd1b7B2YCOQfb
V8wc6BwKZDF9pxFwevzaqFqi0jTR2YCXKs7CWL1hxTiNytNK+M6juyosuf3sG/R53l0g7v
HhhcBm6s+/6GI8TkdueX2o0aDVcKSaO8Ya++54kBpR4rziCFRbwO8B8NY1bokKsdsgyrVk
cAAAdY6qu4h+qruIcAAAAHc3NoLXJzYQAAAgEAuSh8xAZqwezcrgb/hWLrwE58cciH0/3C
NpmEgjC0wlGrgZ2F+ORiqqQfQRdlQrGPx+St8uTy0SJKQdYJOjX46/dTijR6nQG5ZyqH7u
wwq/+LZ9O/jLMjrKPosdUOPV7DoVG7ZiwWefm5IJvgc7KDBaQ3J3wpReGCdEGEmNI+MmRY
a8SNZuk2HscBoBuO8DdIAS2z2za6FAWeP/ok1syXqzdjbuLMrQRlx2yxrIIrOrEE+raLjZ
N4vibRwtfB3HNs1mhmfntShRNtvRPwHsXdfP6IX8sOxh2vT3hjyzWB9IMPFpJy2twrk7/H
KIsBc/Co0K31KoxX2nE1JTfvKMgTJ+bcoDEPe+z0jON7iuhQBn9vOzYAkmFURgQkbfNN7X
GRhukzcwepGyib54Nt0stKNFBq/RuJA+cCLmnH0GoRrONINvxaNrikTj4J9Y5K9+RlG7e4
YJI9Yr9eJ0WpR6LXC2flh70Lwa1ER6w0jfIqZg3ekCjNWl+pFlrls8ERwsiESRqw0Q1vMl
siNHSyTUd1b7B2YCOQfbV8wc6BwKZDF9pxFwevzaqFqi0jTR2YCXKs7CWL1hxTiNytNK+M
6juyosuf3sG/R53l0g7vHhhcBm6s+/6GI8TkdueX2o0aDVcKSaO8Ya++54kBpR4rziCFRb
wO8B8NY1bokKsdsgyrVkcAAAADAQABAAACAD5gM1feSYy2/Mjrtpz67CzGxAmY4pk5/Xlj
Uk6BlgN4e+yYYo+scMjHrXfCJ+zF4IgYs7kGA/8MLDPtpQIlOIxVr6D5eOz3rbvhihWlH+
hxmEcMAJWnq7b3KObvvXJTQFhSLm2HILNKu2EO4hhX5Oe7oJD+tPDDvazofYD2ItnbECaN
+ozWt9K6fAOyBP9LwEgVW2fYEeu40M0AufRazCVz7V1nrkgDGT6LkXdqCqIlDGZhpLW3Hp
AAh925zac0g0/fr9egN/Z4yxlNZDEZuznmjY6n23xGd86v4f6NMhBrLmQORf8Q+OU3UCKK
YZzrUBOs5tDEorwGMz8sjrcQX9MYpEAUCkJfEGqIkLCF6SmPmUSgCobziaIpspke0JNoBX
P+3Wbf1W5ZjLayJvigRBMAP3nb1WNFt1dPIvgPSrl4hARtgCRjwht/V27M3kNlrNYnwskS
Ghr4Kq3G4fUJUhC3sfDB4MZS2BSI/lxPt3PvReE5LT/DHs2A+QOfgrsQIC1lZ9MBOZ6DeO
x+ev8guwUv/VW9W4Fufdw5ayAEVq1vpMfFCsqeXLrU6tWFENgQhFY8NkNpAX9XGA6YUmE2
AIECWYe/6T9zA0opa1VPBde0VmXp5eVSke4MH2n1ZXj3OAM1/3D4HvlufXS3Qt/03QqJUU
wRiXs7ptvZSyvqQCehAAABAAXO//pCeP7N5peyA4JiECh5kha9bzZ9iyF5vumzmIoI9yaK
LG8hQKGUGG+LZvZQIlOtK3uI4qURpFFNvP6Q7OhWQ654+3ikNuzoj7p7Nvsb8aJ4uPQr9Y
eOpmRhWM8GNmnm5iK9ZvLoqiVLJjNjWIlZ/Kq3T13SnT95rzEX8ThDMwHhNAeS7kSONXwX
trck3b2NBYCv9tI8aC3ItWY1ilu+WR7wHSceeKWDUaO3eux7vpP126m5MT+MO7VBsWbgkY
2iVMJnHI9VXsXjmRUgfHUWp/MV8LQgW6K3A0v27MsDxExDpJlP1PqdafWMdZuOgvTfP1lR
usiS1o6TqxTvNc8AAAEBAOApaW3RCYaxa+YB3338tUOomn3Vtp/hkIDO/4UdNZ9vbyfCSF
huyMf2oWKOxKYc6PWcUsBnE7nm76eZtp6fD7fpX1dNqhXDLYUuARE/0TDaXyMzPKeLNU5l
aVxP2OvqcBFsIDVWOp7PwcxBPhzLI481Iv/ZRCsqVqydHF63hjoE1wiXhFBlNpvCoxJoVV
AhIzJKWZm96RKxnWtR22O1bAwM8axtQHW5nIg0zfMWyZIgoiyqHw90YouzHsiKkS6dnPlq
SAzDnoWCgFS+kMxyZefKgCbwA0kDPws0gug59FWhRafKp+P0KN6wb++Cx2CrR5XS08Nv3U
40ckZYCkwcSG8AAAEBANN05IaYytUsXEbh2hdCvgLnNTdano4e5uqjeys4Oq2NQYSezwVy
UyGl2dGWOmDcdfOyXy4sx009yYB0eFbiFPUKgr/3coBvjKJIt4Rh8z4Ibl/1oLfBilbc+8
QEBdUPIxMZIqgKxgXql8/SmR1VwXRSLY8x5tiD1+rf1Toow7liyaSUQEXhAkBdjPwSMzKm
HajWIYwan9ZC7509j7F3Lc737DGmUjI7AYr8Pl93wGIV5IfSe7bY+hu9DT94OwnE6Tejav
P090R27L9j4yTG4RZRGXzeDLheiFTSlhYw18M5oeNgwC2z9CYZDK7ug6IiB4mPyguLMbM+
2aHMNEUpS6kAAAAdYXJ0ZW0tb3NpcG92YXJ0ZW0zMDAyQG1haWwucnUBAgMEBQY= }}
          ssh-known-hosts: ${{ vh304.timeweb.ru ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJi1vvZvbKk4jIGPWVcXioRKZ7Gt27AXHbPEDvFDWYo3L8rhbktPtRrLTZ4T/Kl48Lt7q3+pfXlSDdYpD5GiiiaPJdXaIAKVE4RC9xv8lO4l0n50ZTKtnKQEBSvbacHjqAzHEIOYsJ5T/yuEa7u8l7uXvIR0J5KHKzADv/KoI/A0avj7x9flYF2l3ykDAbtRJHnYULCmp/jC6cGqNxes8hlu9keQXmekysU5RWgGeVcxJl+GNLJl7+v0jO6yJlnrvgqfdXdS1H2IqVMzQ4l+2AcsYVFXZBocTZ/CQ8MySYj7wG3F5lv0EDKk2JaSCcMze4o+6BSms1Sh2qmtehSxKn
vh304.timeweb.ru ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMG6sRsj/dpLnKtzOr+xp6evsBnrxAG8H7zS/4Z0zzDKMzOZykcAw2g3A83IBpSjgHXomE0qK2JURpIUoQNMzVM=
vh304.timeweb.ru ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIxFVM09h5/hQUzZk+wgF7b9KrITU6j/oNy+aj3tJpw2 }}
          remote-username: 'cn73246'
          remote-host: 'online-quiz.ru'
          local-path: 'C:\OpenServer\domains\online-quiz'
          remote-path: '/online-quiz/public_html'
